version: "3.8"

services:
  borg-restore:
    container_name: borg-restore
    image: modem7/borgmatic-docker
    volumes:
      - ${VOLUME_ETC_BORGMATIC}:/etc/borgmatic.d/  # borgmatic config file(s) + crontab.txt
      - ${VOLUME_BORG_CONFIG}:/root/.config/borg   # config and keyfiles
      - ${VOLUME_SSH}:/root/.ssh                   # ssh key for remote repositories
      - ${VOLUME_BORG_CACHE}:/root/.cache/borg     # checksums used for deduplication
      - ./BorgRestoreMountPoint:/RestoreMount
      - ./Restore:/Restore
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
      - label:disable
    environment:
      - TZ=$TZ
      - DOCKERCLI=true
      - BORG_PASSPHRASE=${BORG_PASSPHRASE}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_USER=${DATABASE_USER}
      - BORG_REPO=${BORG_REPO}
      - REPO_LABEL=${REPO_LABEL}
      - RESTORE_HOSTNAME=${RESTORE_HOSTNAME}
      - RESTORE_PORT=${RESTORE_PORT}
      - FORMAT=${FORMAT}
    devices:
      - /dev/fuse:/dev/fuse
    # command: /bin/sh
    networks:
        - magis_images_default
networks:
  magis_images_default:
    external: true

