version: '3.8'
services:
  borgmatic:
    image: 127.0.0.1:5000/borgmatic-custom
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /home/alan/magis:/mnt/docker-compose:ro # Project
      - /var/lib/docker/volumes/magis_magismartech-web-data:/mnt/source:ro # backup source
      - /var/lib/docker/volumes/magis_magismartech-web-data:/mnt/web-data:ro # Volume 1
      - /var/lib/docker/volumes/magis_magismartech-database:/mnt/postgres-data:ro # Volume 2    
      - ./data/borgmatic.d:/etc/borgmatic.d/  # borgmatic config file(s) + crontab.txt
      - ./data/.config/borg:/root/.config/borg   # config and keyfiles
      - ./data/.ssh:/root/.ssh                   # ssh key for remote repositories
      - ./data/.cache/borg:/root/.cache/borg     # checksums used for deduplication
      # - ${VOLUME_TARGET}:/mnt/borg-repository      # backup target
      # - ${VOLUME_BORGMATIC_STATE}:/root/.borgmatic # borgmatic state files
    environment:
      TZ: America/Sao_Paulo
      BACKUP_CRON: /backup_cron
      DEBUG_SECRETS: "true"
      BORG_PASSPHRASE: DOCKER-SECRET->borg_passphrase
      MAGISMARTECH_PASSWORD: DOCKER-SECRET->magismartech_password
      # - BORG_REPO=${BORG_REPO}
    networks:
        - magis_default
    configs:
      - backup_cron
      - tz
    secrets:
      - borg_passphrase
      - magismartech_password

configs:
  backup_cron:
    external: true
  tz:
    external: true

secrets:
  borg_passphrase:
    external: true
  magismartech_password: 
    external: true

networks:
  magis_default:
    driver: overlay
    external: true
